package ec.com.doc.ele.dto;

// Generated 28/12/2011 09:28:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModulousuarioId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ModulousuarioId implements java.io.Serializable {

	private Long codigousuario;
	private String codigomodulo;

	public ModulousuarioId() {
	}

	public ModulousuarioId(Long codigousuario, String codigomodulo) {
		this.codigousuario = codigousuario;
		this.codigomodulo = codigomodulo;
	}

	@Column(name = "codigousuario", nullable = false)
	public Long getCodigousuario() {
		return this.codigousuario;
	}

	public void setCodigousuario(long codigousuario) {
		this.codigousuario = codigousuario;
	}

	@Column(name = "codigomodulo", nullable = false, length = 3)
	public String getCodigomodulo() {
		return this.codigomodulo;
	}

	public void setCodigomodulo(String codigomodulo) {
		this.codigomodulo = codigomodulo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codigomodulo == null) ? 0 : codigomodulo.hashCode());
		result = prime * result
				+ ((codigousuario == null) ? 0 : codigousuario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ModulousuarioId other = (ModulousuarioId) obj;
		if (codigomodulo == null) {
			if (other.codigomodulo != null)
				return false;
		} else if (!codigomodulo.equals(other.codigomodulo))
			return false;
		if (codigousuario == null) {
			if (other.codigousuario != null)
				return false;
		} else if (!codigousuario.equals(other.codigousuario))
			return false;
		return true;
	}
}
