package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * Tclavescontingencia generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tclavescontingencia", schema = "public")
public class Tclavescontingencia extends BuscadorDTO {

	private int idclavescontingencia;
	private Tusuario tusuario;
	private BigDecimal clavecontingencia;
	private String estado;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;
	private Set<Tautcomprobante> tautcomprobantes = new HashSet<Tautcomprobante>(0);

	public Tclavescontingencia() {
	}

	public Tclavescontingencia(int idclavescontingencia) {
		this.idclavescontingencia = idclavescontingencia;
	}

	public Tclavescontingencia(int idclavescontingencia, Tusuario tusuario, BigDecimal clavecontingencia, String estado,
			String usuariomodificacion, Date fecharegistro, Date fechamodificacion,
			Set<Tautcomprobante> tautcomprobantes) {
		this.idclavescontingencia = idclavescontingencia;
		this.tusuario = tusuario;
		this.clavecontingencia = clavecontingencia;
		this.estado = estado;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
		this.tautcomprobantes = tautcomprobantes;
	}

	@Id

	@Column(name = "idclavescontingencia", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdclavescontingencia() {
		return this.idclavescontingencia;
	}

	public void setIdclavescontingencia(int idclavescontingencia) {
		this.idclavescontingencia = idclavescontingencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@Column(name = "clavecontingencia", precision = 49, scale = 0)
	public BigDecimal getClavecontingencia() {
		return this.clavecontingencia;
	}

	public void setClavecontingencia(BigDecimal clavecontingencia) {
		this.clavecontingencia = clavecontingencia;
	}

	@Column(name = "estado", length = 4)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tclavescontingencia")
	public Set<Tautcomprobante> getTautcomprobantes() {
		return this.tautcomprobantes;
	}

	public void setTautcomprobantes(Set<Tautcomprobante> tautcomprobantes) {
		this.tautcomprobantes = tautcomprobantes;
	}

}
