package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tcomprobante generated by hbm2java
 */
@Entity
@Table(name = "tcomprobante", schema = "public")
public class Tcomprobante implements java.io.Serializable {

	private int idcomprobante;
	private Ttipocomprobante ttipocomprobante;
	private Tusuario tusuario;
	private Tcliente tcliente;
	private Integer ambiente;
	private Integer tipoemision;
	private BigDecimal totalbruto;
	private BigDecimal descuentos;
	private BigDecimal totalneto;
	private BigDecimal basesinimp;
	private BigDecimal baseconimp;
	private Integer iva;
	private Integer porivaaplicado;
	private BigDecimal totalfactura;
	private Integer numcomprobante;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;
	private Set<Tdetallecomprobante> tdetallecomprobantes = new HashSet<Tdetallecomprobante>(0);
	private Set<Txmlcomprobante> txmlcomprobantes = new HashSet<Txmlcomprobante>(0);
	private Set<Tautcomprobante> tautcomprobantes = new HashSet<Tautcomprobante>(0);

	public Tcomprobante() {
	}

	public Tcomprobante(int idcomprobante) {
		this.idcomprobante = idcomprobante;
	}

	public Tcomprobante(int idcomprobante, Ttipocomprobante ttipocomprobante, Tusuario tusuario, Tcliente tcliente,
			Integer ambiente, Integer tipoemision, BigDecimal totalbruto, BigDecimal descuentos, BigDecimal totalneto,
			BigDecimal basesinimp, BigDecimal baseconimp, Integer iva, Integer porivaaplicado, BigDecimal totalfactura,
			Integer numcomprobante, String usuariomodificacion, Date fecharegistro, Date fechamodificacion,
			Set<Tdetallecomprobante> tdetallecomprobantes, Set<Txmlcomprobante> txmlcomprobantes,
			Set<Tautcomprobante> tautcomprobantes) {
		this.idcomprobante = idcomprobante;
		this.ttipocomprobante = ttipocomprobante;
		this.tusuario = tusuario;
		this.tcliente = tcliente;
		this.ambiente = ambiente;
		this.tipoemision = tipoemision;
		this.totalbruto = totalbruto;
		this.descuentos = descuentos;
		this.totalneto = totalneto;
		this.basesinimp = basesinimp;
		this.baseconimp = baseconimp;
		this.iva = iva;
		this.porivaaplicado = porivaaplicado;
		this.totalfactura = totalfactura;
		this.numcomprobante = numcomprobante;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
		this.tdetallecomprobantes = tdetallecomprobantes;
		this.txmlcomprobantes = txmlcomprobantes;
		this.tautcomprobantes = tautcomprobantes;
	}

	@Id

	@Column(name = "idcomprobante", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdcomprobante() {
		return this.idcomprobante;
	}

	public void setIdcomprobante(int idcomprobante) {
		this.idcomprobante = idcomprobante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipocomprobante")
	public Ttipocomprobante getTtipocomprobante() {
		return this.ttipocomprobante;
	}

	public void setTtipocomprobante(Ttipocomprobante ttipocomprobante) {
		this.ttipocomprobante = ttipocomprobante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente")
	public Tcliente getTcliente() {
		return this.tcliente;
	}

	public void setTcliente(Tcliente tcliente) {
		this.tcliente = tcliente;
	}

	@Column(name = "ambiente")
	public Integer getAmbiente() {
		return this.ambiente;
	}

	public void setAmbiente(Integer ambiente) {
		this.ambiente = ambiente;
	}

	@Column(name = "tipoemision")
	public Integer getTipoemision() {
		return this.tipoemision;
	}

	public void setTipoemision(Integer tipoemision) {
		this.tipoemision = tipoemision;
	}

	@Column(name = "totalbruto", precision = 10)
	public BigDecimal getTotalbruto() {
		return this.totalbruto;
	}

	public void setTotalbruto(BigDecimal totalbruto) {
		this.totalbruto = totalbruto;
	}

	@Column(name = "descuentos", precision = 10)
	public BigDecimal getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(BigDecimal descuentos) {
		this.descuentos = descuentos;
	}

	@Column(name = "totalneto", precision = 10)
	public BigDecimal getTotalneto() {
		return this.totalneto;
	}

	public void setTotalneto(BigDecimal totalneto) {
		this.totalneto = totalneto;
	}

	@Column(name = "basesinimp", precision = 10)
	public BigDecimal getBasesinimp() {
		return this.basesinimp;
	}

	public void setBasesinimp(BigDecimal basesinimp) {
		this.basesinimp = basesinimp;
	}

	@Column(name = "baseconimp", precision = 10)
	public BigDecimal getBaseconimp() {
		return this.baseconimp;
	}

	public void setBaseconimp(BigDecimal baseconimp) {
		this.baseconimp = baseconimp;
	}

	@Column(name = "iva")
	public Integer getIva() {
		return this.iva;
	}

	public void setIva(Integer iva) {
		this.iva = iva;
	}

	@Column(name = "porivaaplicado")
	public Integer getPorivaaplicado() {
		return this.porivaaplicado;
	}

	public void setPorivaaplicado(Integer porivaaplicado) {
		this.porivaaplicado = porivaaplicado;
	}

	@Column(name = "totalfactura", precision = 10)
	public BigDecimal getTotalfactura() {
		return this.totalfactura;
	}

	public void setTotalfactura(BigDecimal totalfactura) {
		this.totalfactura = totalfactura;
	}

	@Column(name = "numcomprobante")
	public Integer getNumcomprobante() {
		return this.numcomprobante;
	}

	public void setNumcomprobante(Integer numcomprobante) {
		this.numcomprobante = numcomprobante;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tcomprobante")
	public Set<Tdetallecomprobante> getTdetallecomprobantes() {
		return this.tdetallecomprobantes;
	}

	public void setTdetallecomprobantes(Set<Tdetallecomprobante> tdetallecomprobantes) {
		this.tdetallecomprobantes = tdetallecomprobantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tcomprobante")
	public Set<Txmlcomprobante> getTxmlcomprobantes() {
		return this.txmlcomprobantes;
	}

	public void setTxmlcomprobantes(Set<Txmlcomprobante> txmlcomprobantes) {
		this.txmlcomprobantes = txmlcomprobantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tcomprobante")
	public Set<Tautcomprobante> getTautcomprobantes() {
		return this.tautcomprobantes;
	}

	public void setTautcomprobantes(Set<Tautcomprobante> tautcomprobantes) {
		this.tautcomprobantes = tautcomprobantes;
	}

}
