package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * Tdeducibles generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tdeducibles", schema = "public")
public class Tdeducibles extends BuscadorDTO {

	private int iddeducible;
	private Ttipodeducible ttipodeducible;
	private Tproveedor tproveedor;
	private Tusuario tusuario;
	private Tcliente tcliente;
	private BigDecimal valortotaldeducible;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;

	public Tdeducibles() {
	}

	public Tdeducibles(int iddeducible) {
		this.iddeducible = iddeducible;
	}

	public Tdeducibles(int iddeducible, Ttipodeducible ttipodeducible, Tproveedor tproveedor, Tusuario tusuario,
			Tcliente tcliente, BigDecimal valortotaldeducible, String usuariomodificacion, Date fecharegistro,
			Date fechamodificacion) {
		this.iddeducible = iddeducible;
		this.ttipodeducible = ttipodeducible;
		this.tproveedor = tproveedor;
		this.tusuario = tusuario;
		this.tcliente = tcliente;
		this.valortotaldeducible = valortotaldeducible;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
	}

	@Id

	@Column(name = "iddeducible", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIddeducible() {
		return this.iddeducible;
	}

	public void setIddeducible(int iddeducible) {
		this.iddeducible = iddeducible;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipodeducible")
	public Ttipodeducible getTtipodeducible() {
		return this.ttipodeducible;
	}

	public void setTtipodeducible(Ttipodeducible ttipodeducible) {
		this.ttipodeducible = ttipodeducible;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproveedor")
	public Tproveedor getTproveedor() {
		return this.tproveedor;
	}

	public void setTproveedor(Tproveedor tproveedor) {
		this.tproveedor = tproveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente")
	public Tcliente getTcliente() {
		return this.tcliente;
	}

	public void setTcliente(Tcliente tcliente) {
		this.tcliente = tcliente;
	}

	@Column(name = "valortotaldeducible", precision = 10, scale = 4)
	public BigDecimal getValortotaldeducible() {
		return this.valortotaldeducible;
	}

	public void setValortotaldeducible(BigDecimal valortotaldeducible) {
		this.valortotaldeducible = valortotaldeducible;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
