package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * Tdeduciblefactura generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tdeduciblefactura", schema = "public")
public class Tdeduciblefactura extends BuscadorDTO {

	private int iddeduciblefactura;
	private Ttipodeducible ttipodeducible;
	private Tfacturaclienteexterno tfacturaclienteexterno;
	private Tusuario tusuario;
	private BigDecimal totaldeduciblefact;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;

	public Tdeduciblefactura() {
	}

	public Tdeduciblefactura(int iddeduciblefactura) {
		this.iddeduciblefactura = iddeduciblefactura;
	}

	public Tdeduciblefactura(int iddeduciblefactura, Ttipodeducible ttipodeducible,
			Tfacturaclienteexterno tfacturaclienteexterno, Tusuario tusuario, BigDecimal totaldeduciblefact,
			String usuariomodificacion, Date fecharegistro, Date fechamodificacion) {
		this.iddeduciblefactura = iddeduciblefactura;
		this.ttipodeducible = ttipodeducible;
		this.tfacturaclienteexterno = tfacturaclienteexterno;
		this.tusuario = tusuario;
		this.totaldeduciblefact = totaldeduciblefact;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
	}

	@Id

	@Column(name = "iddeduciblefactura", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIddeduciblefactura() {
		return this.iddeduciblefactura;
	}

	public void setIddeduciblefactura(int iddeduciblefactura) {
		this.iddeduciblefactura = iddeduciblefactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipodeducible")
	public Ttipodeducible getTtipodeducible() {
		return this.ttipodeducible;
	}

	public void setTtipodeducible(Ttipodeducible ttipodeducible) {
		this.ttipodeducible = ttipodeducible;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfactclienteext")
	public Tfacturaclienteexterno getTfacturaclienteexterno() {
		return this.tfacturaclienteexterno;
	}

	public void setTfacturaclienteexterno(Tfacturaclienteexterno tfacturaclienteexterno) {
		this.tfacturaclienteexterno = tfacturaclienteexterno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@Column(name = "totaldeduciblefact", precision = 10, scale = 4)
	public BigDecimal getTotaldeduciblefact() {
		return this.totaldeduciblefact;
	}

	public void setTotaldeduciblefact(BigDecimal totaldeduciblefact) {
		this.totaldeduciblefact = totaldeduciblefact;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
