package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tdetallefactext generated by hbm2java
 */
@Entity
@Table(name = "tdetallefactext", schema = "public")
public class Tdetallefactext implements java.io.Serializable {

	private int iddetallefactext;
	private Ttipodeducible ttipodeducible;
	private Tfacturaclienteexterno tfacturaclienteexterno;
	private Tusuario tusuario;
	private BigDecimal codigodebarras;
	private String descripcion;
	private BigDecimal preciounisinimp;
	private BigDecimal preciouniconimo;
	private Integer ivaaplicado;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;

	public Tdetallefactext() {
	}

	public Tdetallefactext(int iddetallefactext) {
		this.iddetallefactext = iddetallefactext;
	}

	public Tdetallefactext(int iddetallefactext, Ttipodeducible ttipodeducible,
			Tfacturaclienteexterno tfacturaclienteexterno, Tusuario tusuario, BigDecimal codigodebarras,
			String descripcion, BigDecimal preciounisinimp, BigDecimal preciouniconimo, Integer ivaaplicado,
			String usuariomodificacion, Date fecharegistro, Date fechamodificacion) {
		this.iddetallefactext = iddetallefactext;
		this.ttipodeducible = ttipodeducible;
		this.tfacturaclienteexterno = tfacturaclienteexterno;
		this.tusuario = tusuario;
		this.codigodebarras = codigodebarras;
		this.descripcion = descripcion;
		this.preciounisinimp = preciounisinimp;
		this.preciouniconimo = preciouniconimo;
		this.ivaaplicado = ivaaplicado;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
	}

	@Id

	@Column(name = "iddetallefactext", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIddetallefactext() {
		return this.iddetallefactext;
	}

	public void setIddetallefactext(int iddetallefactext) {
		this.iddetallefactext = iddetallefactext;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipodeducible")
	public Ttipodeducible getTtipodeducible() {
		return this.ttipodeducible;
	}

	public void setTtipodeducible(Ttipodeducible ttipodeducible) {
		this.ttipodeducible = ttipodeducible;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfactclienteext")
	public Tfacturaclienteexterno getTfacturaclienteexterno() {
		return this.tfacturaclienteexterno;
	}

	public void setTfacturaclienteexterno(Tfacturaclienteexterno tfacturaclienteexterno) {
		this.tfacturaclienteexterno = tfacturaclienteexterno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@Column(name = "codigodebarras", precision = 64, scale = 0)
	public BigDecimal getCodigodebarras() {
		return this.codigodebarras;
	}

	public void setCodigodebarras(BigDecimal codigodebarras) {
		this.codigodebarras = codigodebarras;
	}

	@Column(name = "descripcion", length = 128)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "preciounisinimp", precision = 10, scale = 4)
	public BigDecimal getPreciounisinimp() {
		return this.preciounisinimp;
	}

	public void setPreciounisinimp(BigDecimal preciounisinimp) {
		this.preciounisinimp = preciounisinimp;
	}

	@Column(name = "preciouniconimo", precision = 10, scale = 4)
	public BigDecimal getPreciouniconimo() {
		return this.preciouniconimo;
	}

	public void setPreciouniconimo(BigDecimal preciouniconimo) {
		this.preciouniconimo = preciouniconimo;
	}

	@Column(name = "ivaaplicado")
	public Integer getIvaaplicado() {
		return this.ivaaplicado;
	}

	public void setIvaaplicado(Integer ivaaplicado) {
		this.ivaaplicado = ivaaplicado;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
