package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * Tdetallecomprobante generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tdetallecomprobante", schema = "public")
public class Tdetallecomprobante extends BuscadorDTO {

	private int iddetalle;
	private Tcomprobante tcomprobante;
	private Tcatalogoarticulos tcatalogoarticulos;
	private Tusuario tusuario;
	private BigDecimal codigodebarras;
	private String descripcion;
	private BigDecimal preciounisinimp;
	private BigDecimal preciouniconimo;
	private Integer ivaaplicado;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;

	public Tdetallecomprobante() {
	}

	public Tdetallecomprobante(int iddetalle) {
		this.iddetalle = iddetalle;
	}

	public Tdetallecomprobante(int iddetalle, Tcomprobante tcomprobante, Tcatalogoarticulos tcatalogoarticulos,
			Tusuario tusuario, BigDecimal codigodebarras, String descripcion, BigDecimal preciounisinimp,
			BigDecimal preciouniconimo, Integer ivaaplicado, String usuariomodificacion, Date fecharegistro,
			Date fechamodificacion) {
		this.iddetalle = iddetalle;
		this.tcomprobante = tcomprobante;
		this.tcatalogoarticulos = tcatalogoarticulos;
		this.tusuario = tusuario;
		this.codigodebarras = codigodebarras;
		this.descripcion = descripcion;
		this.preciounisinimp = preciounisinimp;
		this.preciouniconimo = preciouniconimo;
		this.ivaaplicado = ivaaplicado;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
	}

	@Id

	@Column(name = "iddetalle", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIddetalle() {
		return this.iddetalle;
	}

	public void setIddetalle(int iddetalle) {
		this.iddetalle = iddetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcomprobante")
	public Tcomprobante getTcomprobante() {
		return this.tcomprobante;
	}

	public void setTcomprobante(Tcomprobante tcomprobante) {
		this.tcomprobante = tcomprobante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idarticulo")
	public Tcatalogoarticulos getTcatalogoarticulos() {
		return this.tcatalogoarticulos;
	}

	public void setTcatalogoarticulos(Tcatalogoarticulos tcatalogoarticulos) {
		this.tcatalogoarticulos = tcatalogoarticulos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@Column(name = "codigodebarras", precision = 64, scale = 0)
	public BigDecimal getCodigodebarras() {
		return this.codigodebarras;
	}

	public void setCodigodebarras(BigDecimal codigodebarras) {
		this.codigodebarras = codigodebarras;
	}

	@Column(name = "descripcion", length = 128)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "preciounisinimp", precision = 10, scale = 4)
	public BigDecimal getPreciounisinimp() {
		return this.preciounisinimp;
	}

	public void setPreciounisinimp(BigDecimal preciounisinimp) {
		this.preciounisinimp = preciounisinimp;
	}

	@Column(name = "preciouniconimo", precision = 10, scale = 4)
	public BigDecimal getPreciouniconimo() {
		return this.preciouniconimo;
	}

	public void setPreciouniconimo(BigDecimal preciouniconimo) {
		this.preciouniconimo = preciouniconimo;
	}

	@Column(name = "ivaaplicado")
	public Integer getIvaaplicado() {
		return this.ivaaplicado;
	}

	public void setIvaaplicado(Integer ivaaplicado) {
		this.ivaaplicado = ivaaplicado;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
