package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * Tfacturaclienteexterno generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tfacturaclienteexterno", schema = "public")
public class Tfacturaclienteexterno extends BuscadorDTO {

	private int idfactclienteext;
	private Tproveedor tproveedor;
	private Tusuario tusuario;
	private Tcliente tcliente;
	private Integer ambiente;
	private Integer tipoemision;
	private BigDecimal totalbruto;
	private BigDecimal descuentos;
	private BigDecimal totalneto;
	private BigDecimal basesinimp;
	private BigDecimal baseconimp;
	private Integer iva;
	private Integer porivaaplicado;
	private BigDecimal totalfactura;
	private Integer numcomprobante;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;
	private Set<Tdetallefactext> tdetallefactexts = new HashSet<Tdetallefactext>(0);
	private Set<Tdeduciblefactura> tdeduciblefacturas = new HashSet<Tdeduciblefactura>(0);

	public Tfacturaclienteexterno() {
	}

	public Tfacturaclienteexterno(int idfactclienteext) {
		this.idfactclienteext = idfactclienteext;
	}

	public Tfacturaclienteexterno(int idfactclienteext, Tproveedor tproveedor, Tusuario tusuario, Tcliente tcliente,
			Integer ambiente, Integer tipoemision, BigDecimal totalbruto, BigDecimal descuentos, BigDecimal totalneto,
			BigDecimal basesinimp, BigDecimal baseconimp, Integer iva, Integer porivaaplicado, BigDecimal totalfactura,
			Integer numcomprobante, String usuariomodificacion, Date fecharegistro, Date fechamodificacion,
			Set<Tdetallefactext> tdetallefactexts, Set<Tdeduciblefactura> tdeduciblefacturas) {
		this.idfactclienteext = idfactclienteext;
		this.tproveedor = tproveedor;
		this.tusuario = tusuario;
		this.tcliente = tcliente;
		this.ambiente = ambiente;
		this.tipoemision = tipoemision;
		this.totalbruto = totalbruto;
		this.descuentos = descuentos;
		this.totalneto = totalneto;
		this.basesinimp = basesinimp;
		this.baseconimp = baseconimp;
		this.iva = iva;
		this.porivaaplicado = porivaaplicado;
		this.totalfactura = totalfactura;
		this.numcomprobante = numcomprobante;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
		this.tdetallefactexts = tdetallefactexts;
		this.tdeduciblefacturas = tdeduciblefacturas;
	}

	@Id

	@Column(name = "idfactclienteext", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdfactclienteext() {
		return this.idfactclienteext;
	}

	public void setIdfactclienteext(int idfactclienteext) {
		this.idfactclienteext = idfactclienteext;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproveedor")
	public Tproveedor getTproveedor() {
		return this.tproveedor;
	}

	public void setTproveedor(Tproveedor tproveedor) {
		this.tproveedor = tproveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente")
	public Tcliente getTcliente() {
		return this.tcliente;
	}

	public void setTcliente(Tcliente tcliente) {
		this.tcliente = tcliente;
	}

	@Column(name = "ambiente")
	public Integer getAmbiente() {
		return this.ambiente;
	}

	public void setAmbiente(Integer ambiente) {
		this.ambiente = ambiente;
	}

	@Column(name = "tipoemision")
	public Integer getTipoemision() {
		return this.tipoemision;
	}

	public void setTipoemision(Integer tipoemision) {
		this.tipoemision = tipoemision;
	}

	@Column(name = "totalbruto", precision = 10)
	public BigDecimal getTotalbruto() {
		return this.totalbruto;
	}

	public void setTotalbruto(BigDecimal totalbruto) {
		this.totalbruto = totalbruto;
	}

	@Column(name = "descuentos", precision = 10)
	public BigDecimal getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(BigDecimal descuentos) {
		this.descuentos = descuentos;
	}

	@Column(name = "totalneto", precision = 10)
	public BigDecimal getTotalneto() {
		return this.totalneto;
	}

	public void setTotalneto(BigDecimal totalneto) {
		this.totalneto = totalneto;
	}

	@Column(name = "basesinimp", precision = 10)
	public BigDecimal getBasesinimp() {
		return this.basesinimp;
	}

	public void setBasesinimp(BigDecimal basesinimp) {
		this.basesinimp = basesinimp;
	}

	@Column(name = "baseconimp", precision = 10)
	public BigDecimal getBaseconimp() {
		return this.baseconimp;
	}

	public void setBaseconimp(BigDecimal baseconimp) {
		this.baseconimp = baseconimp;
	}

	@Column(name = "iva")
	public Integer getIva() {
		return this.iva;
	}

	public void setIva(Integer iva) {
		this.iva = iva;
	}

	@Column(name = "porivaaplicado")
	public Integer getPorivaaplicado() {
		return this.porivaaplicado;
	}

	public void setPorivaaplicado(Integer porivaaplicado) {
		this.porivaaplicado = porivaaplicado;
	}

	@Column(name = "totalfactura", precision = 10)
	public BigDecimal getTotalfactura() {
		return this.totalfactura;
	}

	public void setTotalfactura(BigDecimal totalfactura) {
		this.totalfactura = totalfactura;
	}

	@Column(name = "numcomprobante")
	public Integer getNumcomprobante() {
		return this.numcomprobante;
	}

	public void setNumcomprobante(Integer numcomprobante) {
		this.numcomprobante = numcomprobante;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfacturaclienteexterno")
	public Set<Tdetallefactext> getTdetallefactexts() {
		return this.tdetallefactexts;
	}

	public void setTdetallefactexts(Set<Tdetallefactext> tdetallefactexts) {
		this.tdetallefactexts = tdetallefactexts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfacturaclienteexterno")
	public Set<Tdeduciblefactura> getTdeduciblefacturas() {
		return this.tdeduciblefacturas;
	}

	public void setTdeduciblefacturas(Set<Tdeduciblefactura> tdeduciblefacturas) {
		this.tdeduciblefacturas = tdeduciblefacturas;
	}

}
