package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tfirmaelectronica generated by hbm2java
 */
@Entity
@Table(name = "tfirmaelectronica", schema = "public")
public class Tfirmaelectronica implements java.io.Serializable {

	private int idfirmaelectronica;
	private Tusuario tusuario;
	private String archivofirele;
	private String estadofirele;
	private Date vigencia;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;
	private Set<Tautcomprobante> tautcomprobantes = new HashSet<Tautcomprobante>(0);

	public Tfirmaelectronica() {
	}

	public Tfirmaelectronica(int idfirmaelectronica) {
		this.idfirmaelectronica = idfirmaelectronica;
	}

	public Tfirmaelectronica(int idfirmaelectronica, Tusuario tusuario, String archivofirele, String estadofirele,
			Date vigencia, String usuariomodificacion, Date fecharegistro, Date fechamodificacion,
			Set<Tautcomprobante> tautcomprobantes) {
		this.idfirmaelectronica = idfirmaelectronica;
		this.tusuario = tusuario;
		this.archivofirele = archivofirele;
		this.estadofirele = estadofirele;
		this.vigencia = vigencia;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
		this.tautcomprobantes = tautcomprobantes;
	}

	@Id

	@Column(name = "idfirmaelectronica", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdfirmaelectronica() {
		return this.idfirmaelectronica;
	}

	public void setIdfirmaelectronica(int idfirmaelectronica) {
		this.idfirmaelectronica = idfirmaelectronica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@Column(name = "archivofirele", length = 2048)
	public String getArchivofirele() {
		return this.archivofirele;
	}

	public void setArchivofirele(String archivofirele) {
		this.archivofirele = archivofirele;
	}

	@Column(name = "estadofirele", length = 4)
	public String getEstadofirele() {
		return this.estadofirele;
	}

	public void setEstadofirele(String estadofirele) {
		this.estadofirele = estadofirele;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vigencia", length = 4)
	public Date getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(Date vigencia) {
		this.vigencia = vigencia;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfirmaelectronica")
	public Set<Tautcomprobante> getTautcomprobantes() {
		return this.tautcomprobantes;
	}

	public void setTautcomprobantes(Set<Tautcomprobante> tautcomprobantes) {
		this.tautcomprobantes = tautcomprobantes;
	}

}
