package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * Tproveedor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tproveedor", schema = "public")
public class Tproveedor extends BuscadorDTO {

	private int idproveedor;
	private Tusuario tusuario;
	private String numdocproveedor;
	private String estadoproveedor;
	private String usuariomodificacion;
	private Date fecharegistrio;
	private Date fechamodificacion;
	private Set<Tfacturaclienteexterno> tfacturaclienteexternos = new HashSet<Tfacturaclienteexterno>(0);
	private Set<Tdeducibles> tdeducibleses = new HashSet<Tdeducibles>(0);

	public Tproveedor() {
	}

	public Tproveedor(int idproveedor) {
		this.idproveedor = idproveedor;
	}

	public Tproveedor(int idproveedor, Tusuario tusuario, String numdocproveedor, String estadoproveedor,
			String usuariomodificacion, Date fecharegistrio, Date fechamodificacion,
			Set<Tfacturaclienteexterno> tfacturaclienteexternos, Set<Tdeducibles> tdeducibleses) {
		this.idproveedor = idproveedor;
		this.tusuario = tusuario;
		this.numdocproveedor = numdocproveedor;
		this.estadoproveedor = estadoproveedor;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistrio = fecharegistrio;
		this.fechamodificacion = fechamodificacion;
		this.tfacturaclienteexternos = tfacturaclienteexternos;
		this.tdeducibleses = tdeducibleses;
	}

	@Id

	@Column(name = "idproveedor", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdproveedor() {
		return this.idproveedor;
	}

	public void setIdproveedor(int idproveedor) {
		this.idproveedor = idproveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@Column(name = "numdocproveedor", length = 13)
	public String getNumdocproveedor() {
		return this.numdocproveedor;
	}

	public void setNumdocproveedor(String numdocproveedor) {
		this.numdocproveedor = numdocproveedor;
	}

	@Column(name = "estadoproveedor", length = 4)
	public String getEstadoproveedor() {
		return this.estadoproveedor;
	}

	public void setEstadoproveedor(String estadoproveedor) {
		this.estadoproveedor = estadoproveedor;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistrio", length = 4)
	public Date getFecharegistrio() {
		return this.fecharegistrio;
	}

	public void setFecharegistrio(Date fecharegistrio) {
		this.fecharegistrio = fecharegistrio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tproveedor")
	public Set<Tfacturaclienteexterno> getTfacturaclienteexternos() {
		return this.tfacturaclienteexternos;
	}

	public void setTfacturaclienteexternos(Set<Tfacturaclienteexterno> tfacturaclienteexternos) {
		this.tfacturaclienteexternos = tfacturaclienteexternos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tproveedor")
	public Set<Tdeducibles> getTdeducibleses() {
		return this.tdeducibleses;
	}

	public void setTdeducibleses(Set<Tdeducibles> tdeducibleses) {
		this.tdeducibleses = tdeducibleses;
	}

}
