package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tpuntoemision generated by hbm2java
 */
@Entity
@Table(name = "tpuntoemision", schema = "public")
public class Tpuntoemision implements java.io.Serializable {

	private int idpuntoemision;
	private Tusuario tusuario;
	private Testablecimiento testablecimiento;
	private String nombrepuntoemision;
	private String codigopuntoemision;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;

	public Tpuntoemision() {
	}

	public Tpuntoemision(int idpuntoemision) {
		this.idpuntoemision = idpuntoemision;
	}

	public Tpuntoemision(int idpuntoemision, Tusuario tusuario, Testablecimiento testablecimiento,
			String nombrepuntoemision, String codigopuntoemision, String usuariomodificacion, Date fecharegistro,
			Date fechamodificacion) {
		this.idpuntoemision = idpuntoemision;
		this.tusuario = tusuario;
		this.testablecimiento = testablecimiento;
		this.nombrepuntoemision = nombrepuntoemision;
		this.codigopuntoemision = codigopuntoemision;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
	}

	@Id

	@Column(name = "idpuntoemision", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdpuntoemision() {
		return this.idpuntoemision;
	}

	public void setIdpuntoemision(int idpuntoemision) {
		this.idpuntoemision = idpuntoemision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestablecimiento")
	public Testablecimiento getTestablecimiento() {
		return this.testablecimiento;
	}

	public void setTestablecimiento(Testablecimiento testablecimiento) {
		this.testablecimiento = testablecimiento;
	}

	@Column(name = "nombrepuntoemision", length = 128)
	public String getNombrepuntoemision() {
		return this.nombrepuntoemision;
	}

	public void setNombrepuntoemision(String nombrepuntoemision) {
		this.nombrepuntoemision = nombrepuntoemision;
	}

	@Column(name = "codigopuntoemision", length = 64)
	public String getCodigopuntoemision() {
		return this.codigopuntoemision;
	}

	public void setCodigopuntoemision(String codigopuntoemision) {
		this.codigopuntoemision = codigopuntoemision;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
