package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * Tusuario generated by hbm2java
 */
@Entity
@Table(name = "tusuario", schema = "public")
public class Tusuario extends BuscadorDTO {

	private Long idusuario;
	private String cuentausuario;
	private String nombreusuario;
	private String claveusuario;
	private String estadousuario;
	private String tipousuario;
	private Date fecharegistro;
	private Date fechamodificacion;
	private String usuarioregistro;
	private String usuariomodificacion;
	private Set<Tdetallecomprobante> tdetallecomprobantes = new HashSet<Tdetallecomprobante>(0);
	private Set<Tdeducibles> tdeducibleses = new HashSet<Tdeducibles>(0);
	private Set<Tpuntoemision> tpuntoemisions = new HashSet<Tpuntoemision>(0);
	private Set<Ttipodocumento> ttipodocumentos = new HashSet<Ttipodocumento>(0);
	private Set<Tproveedor> tproveedors = new HashSet<Tproveedor>(0);
	private Set<Ttipocomprobante> ttipocomprobantes = new HashSet<Ttipocomprobante>(0);
	private Set<Tmenu> tmenus = new HashSet<Tmenu>(0);
	private Set<Txmlcomprobante> txmlcomprobantes = new HashSet<Txmlcomprobante>(0);
	private Set<Tautcomprobante> tautcomprobantes = new HashSet<Tautcomprobante>(0);
	private Set<Tusuariomenu> tusuariomenus = new HashSet<Tusuariomenu>(0);
	private Set<Tcatalogoarticulos> tcatalogoarticuloses = new HashSet<Tcatalogoarticulos>(0);
	private Set<Tcomprobante> tcomprobantes = new HashSet<Tcomprobante>(0);
	private Set<Tdetallefactext> tdetallefactexts = new HashSet<Tdetallefactext>(0);
	private Set<Tfacturaclienteexterno> tfacturaclienteexternos = new HashSet<Tfacturaclienteexterno>(0);
	private Set<Tcliente> tclientes = new HashSet<Tcliente>(0);
	private Set<Tfirmaelectronica> tfirmaelectronicas = new HashSet<Tfirmaelectronica>(0);
	private Set<Ttipodeducible> ttipodeducibles = new HashSet<Ttipodeducible>(0);
	private Set<Testablecimiento> testablecimientos = new HashSet<Testablecimiento>(0);
	private Set<Tdeduciblefactura> tdeduciblefacturas = new HashSet<Tdeduciblefactura>(0);
	private Set<Tclavescontingencia> tclavescontingencias = new HashSet<Tclavescontingencia>(0);

	public Tusuario() {
	}

	public Tusuario(Long idusuario) {
		this.idusuario = idusuario;
	}

	public Tusuario(Long idusuario, String cuentausuario, String nombreusuario, String claveusuario,
			String estadousuario, String tipousuario, Date fecharegistro, Date fechamodificacion,
			String usuarioregistro, String usuariomodificacion, Set<Tdetallecomprobante> tdetallecomprobantes,
			Set<Tdeducibles> tdeducibleses, Set<Tpuntoemision> tpuntoemisions, Set<Ttipodocumento> ttipodocumentos,
			Set<Tproveedor> tproveedors, Set<Ttipocomprobante> ttipocomprobantes, Set<Tmenu> tmenus,
			Set<Txmlcomprobante> txmlcomprobantes, Set<Tautcomprobante> tautcomprobantes,
			Set<Tusuariomenu> tusuariomenus, Set<Tcatalogoarticulos> tcatalogoarticuloses,
			Set<Tcomprobante> tcomprobantes, Set<Tdetallefactext> tdetallefactexts,
			Set<Tfacturaclienteexterno> tfacturaclienteexternos, Set<Tcliente> tclientes,
			Set<Tfirmaelectronica> tfirmaelectronicas, Set<Ttipodeducible> ttipodeducibles,
			Set<Testablecimiento> testablecimientos, Set<Tdeduciblefactura> tdeduciblefacturas,
			Set<Tclavescontingencia> tclavescontingencias) {
		this.idusuario = idusuario;
		this.cuentausuario = cuentausuario;
		this.nombreusuario = nombreusuario;
		this.claveusuario = claveusuario;
		this.estadousuario = estadousuario;
		this.tipousuario = tipousuario;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
		this.usuarioregistro = usuarioregistro;
		this.usuariomodificacion = usuariomodificacion;
		this.tdetallecomprobantes = tdetallecomprobantes;
		this.tdeducibleses = tdeducibleses;
		this.tpuntoemisions = tpuntoemisions;
		this.ttipodocumentos = ttipodocumentos;
		this.tproveedors = tproveedors;
		this.ttipocomprobantes = ttipocomprobantes;
		this.tmenus = tmenus;
		this.txmlcomprobantes = txmlcomprobantes;
		this.tautcomprobantes = tautcomprobantes;
		this.tusuariomenus = tusuariomenus;
		this.tcatalogoarticuloses = tcatalogoarticuloses;
		this.tcomprobantes = tcomprobantes;
		this.tdetallefactexts = tdetallefactexts;
		this.tfacturaclienteexternos = tfacturaclienteexternos;
		this.tclientes = tclientes;
		this.tfirmaelectronicas = tfirmaelectronicas;
		this.ttipodeducibles = ttipodeducibles;
		this.testablecimientos = testablecimientos;
		this.tdeduciblefacturas = tdeduciblefacturas;
		this.tclavescontingencias = tclavescontingencias;
	}

	@Id

	@Column(name = "idusuario", unique = true, nullable = false, precision = 9, scale = 0)
	public Long getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Long idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "cuentausuario", length = 64)
	public String getCuentausuario() {
		return this.cuentausuario;
	}

	public void setCuentausuario(String cuentausuario) {
		this.cuentausuario = cuentausuario;
	}

	@Column(name = "nombreusuario", length = 128)
	public String getNombreusuario() {
		return this.nombreusuario;
	}

	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	@Column(name = "claveusuario", length = 128)
	public String getClaveusuario() {
		return this.claveusuario;
	}

	public void setClaveusuario(String claveusuario) {
		this.claveusuario = claveusuario;
	}

	@Column(name = "estadousuario", length = 128)
	public String getEstadousuario() {
		return this.estadousuario;
	}

	public void setEstadousuario(String estadousuario) {
		this.estadousuario = estadousuario;
	}

	@Column(name = "tipousuario", length = 64)
	public String getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(String tipousuario) {
		this.tipousuario = tipousuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@Column(name = "usuarioregistro", length = 64)
	public String getUsuarioregistro() {
		return this.usuarioregistro;
	}

	public void setUsuarioregistro(String usuarioregistro) {
		this.usuarioregistro = usuarioregistro;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tdetallecomprobante> getTdetallecomprobantes() {
		return this.tdetallecomprobantes;
	}

	public void setTdetallecomprobantes(Set<Tdetallecomprobante> tdetallecomprobantes) {
		this.tdetallecomprobantes = tdetallecomprobantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tdeducibles> getTdeducibleses() {
		return this.tdeducibleses;
	}

	public void setTdeducibleses(Set<Tdeducibles> tdeducibleses) {
		this.tdeducibleses = tdeducibleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tpuntoemision> getTpuntoemisions() {
		return this.tpuntoemisions;
	}

	public void setTpuntoemisions(Set<Tpuntoemision> tpuntoemisions) {
		this.tpuntoemisions = tpuntoemisions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Ttipodocumento> getTtipodocumentos() {
		return this.ttipodocumentos;
	}

	public void setTtipodocumentos(Set<Ttipodocumento> ttipodocumentos) {
		this.ttipodocumentos = ttipodocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tproveedor> getTproveedors() {
		return this.tproveedors;
	}

	public void setTproveedors(Set<Tproveedor> tproveedors) {
		this.tproveedors = tproveedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Ttipocomprobante> getTtipocomprobantes() {
		return this.ttipocomprobantes;
	}

	public void setTtipocomprobantes(Set<Ttipocomprobante> ttipocomprobantes) {
		this.ttipocomprobantes = ttipocomprobantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tmenu> getTmenus() {
		return this.tmenus;
	}

	public void setTmenus(Set<Tmenu> tmenus) {
		this.tmenus = tmenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Txmlcomprobante> getTxmlcomprobantes() {
		return this.txmlcomprobantes;
	}

	public void setTxmlcomprobantes(Set<Txmlcomprobante> txmlcomprobantes) {
		this.txmlcomprobantes = txmlcomprobantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tautcomprobante> getTautcomprobantes() {
		return this.tautcomprobantes;
	}

	public void setTautcomprobantes(Set<Tautcomprobante> tautcomprobantes) {
		this.tautcomprobantes = tautcomprobantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tusuariomenu> getTusuariomenus() {
		return this.tusuariomenus;
	}

	public void setTusuariomenus(Set<Tusuariomenu> tusuariomenus) {
		this.tusuariomenus = tusuariomenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tcatalogoarticulos> getTcatalogoarticuloses() {
		return this.tcatalogoarticuloses;
	}

	public void setTcatalogoarticuloses(Set<Tcatalogoarticulos> tcatalogoarticuloses) {
		this.tcatalogoarticuloses = tcatalogoarticuloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tcomprobante> getTcomprobantes() {
		return this.tcomprobantes;
	}

	public void setTcomprobantes(Set<Tcomprobante> tcomprobantes) {
		this.tcomprobantes = tcomprobantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tdetallefactext> getTdetallefactexts() {
		return this.tdetallefactexts;
	}

	public void setTdetallefactexts(Set<Tdetallefactext> tdetallefactexts) {
		this.tdetallefactexts = tdetallefactexts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tfacturaclienteexterno> getTfacturaclienteexternos() {
		return this.tfacturaclienteexternos;
	}

	public void setTfacturaclienteexternos(Set<Tfacturaclienteexterno> tfacturaclienteexternos) {
		this.tfacturaclienteexternos = tfacturaclienteexternos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tcliente> getTclientes() {
		return this.tclientes;
	}

	public void setTclientes(Set<Tcliente> tclientes) {
		this.tclientes = tclientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tfirmaelectronica> getTfirmaelectronicas() {
		return this.tfirmaelectronicas;
	}

	public void setTfirmaelectronicas(Set<Tfirmaelectronica> tfirmaelectronicas) {
		this.tfirmaelectronicas = tfirmaelectronicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Ttipodeducible> getTtipodeducibles() {
		return this.ttipodeducibles;
	}

	public void setTtipodeducibles(Set<Ttipodeducible> ttipodeducibles) {
		this.ttipodeducibles = ttipodeducibles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Testablecimiento> getTestablecimientos() {
		return this.testablecimientos;
	}

	public void setTestablecimientos(Set<Testablecimiento> testablecimientos) {
		this.testablecimientos = testablecimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tdeduciblefactura> getTdeduciblefacturas() {
		return this.tdeduciblefacturas;
	}

	public void setTdeduciblefacturas(Set<Tdeduciblefactura> tdeduciblefacturas) {
		this.tdeduciblefacturas = tdeduciblefacturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tusuario")
	public Set<Tclavescontingencia> getTclavescontingencias() {
		return this.tclavescontingencias;
	}

	public void setTclavescontingencias(Set<Tclavescontingencia> tclavescontingencias) {
		this.tclavescontingencias = tclavescontingencias;
	}

}
