package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import ec.com.doc.ele.pojo.BuscadorDTO;

/**
 * TusuariomenuId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class TusuariomenuId extends BuscadorDTO {

	private Long idusuario;
	private Long idmenu;

	public TusuariomenuId() {
	}

	public TusuariomenuId(Long idusuario, Long idmenu) {
		this.idusuario = idusuario;
		this.idmenu = idmenu;
	}

	@Column(name = "idusuario", nullable = false, precision = 9, scale = 0)
	public Long getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Long idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idmenu", nullable = false, precision = 9, scale = 0)
	public Long getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(Long idmenu) {
		this.idmenu = idmenu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TusuariomenuId))
			return false;
		TusuariomenuId castOther = (TusuariomenuId) other;

		return (this.getIdusuario() == castOther.getIdusuario()) && (this.getIdmenu() == castOther.getIdmenu());
	}
}
