package ec.com.doc.ele.dto;
// Generated 11-may-2016 8:40:33 by Hibernate Tools 4.0.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txmlcomprobante generated by hbm2java
 */
@Entity
@Table(name = "txmlcomprobante", schema = "public")
public class Txmlcomprobante implements java.io.Serializable {

	private int idxmlcomprobante;
	private Tcomprobante tcomprobante;
	private Tusuario tusuario;
	private String documentoxml;
	private String usuariomodificacion;
	private Date fecharegistro;
	private Date fechamodificacion;

	public Txmlcomprobante() {
	}

	public Txmlcomprobante(int idxmlcomprobante) {
		this.idxmlcomprobante = idxmlcomprobante;
	}

	public Txmlcomprobante(int idxmlcomprobante, Tcomprobante tcomprobante, Tusuario tusuario, String documentoxml,
			String usuariomodificacion, Date fecharegistro, Date fechamodificacion) {
		this.idxmlcomprobante = idxmlcomprobante;
		this.tcomprobante = tcomprobante;
		this.tusuario = tusuario;
		this.documentoxml = documentoxml;
		this.usuariomodificacion = usuariomodificacion;
		this.fecharegistro = fecharegistro;
		this.fechamodificacion = fechamodificacion;
	}

	@Id

	@Column(name = "idxmlcomprobante", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdxmlcomprobante() {
		return this.idxmlcomprobante;
	}

	public void setIdxmlcomprobante(int idxmlcomprobante) {
		this.idxmlcomprobante = idxmlcomprobante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcomprobante")
	public Tcomprobante getTcomprobante() {
		return this.tcomprobante;
	}

	public void setTcomprobante(Tcomprobante tcomprobante) {
		this.tcomprobante = tcomprobante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioregistro")
	public Tusuario getTusuario() {
		return this.tusuario;
	}

	public void setTusuario(Tusuario tusuario) {
		this.tusuario = tusuario;
	}

	@Column(name = "documentoxml", length = 2048)
	public String getDocumentoxml() {
		return this.documentoxml;
	}

	public void setDocumentoxml(String documentoxml) {
		this.documentoxml = documentoxml;
	}

	@Column(name = "usuariomodificacion", length = 64)
	public String getUsuariomodificacion() {
		return this.usuariomodificacion;
	}

	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", length = 4)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamodificacion", length = 4)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
